export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const SET_LOGIN_TOKEN = 'SET_LOGIN_TOKEN';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
